project:
  type: website

website:
  title: "Nikhil Rachagani"
  favicon: "images/nikhil.jpeg"
  site-url: https://www.myblogexample.io
  page-footer:
    center: |
      [Contact Nikhil Rachagani](mailto:nikhil. nikhilrachagani@my.unt.edu )
    left: |
      Made with [Nikhil Rachagani](https://github.com/RachaganiNikhil)
    right: |
      [Github Code Repo](https://github.com/RachaganiNikhil/nikhil_portfolio.git)
    background: "#B40080"
    
  
  navbar:
    left:
      - icon: rss
      - href: index.qmd
        text: Home
      - href: blog.qmd
        text: my blog post
      - href: resume.qmd
        text: Resume
        
    right:
      - icon: github
        href: https://github.com/RachaganiNikhil
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: minty
    css: styles.css

editor: visual

